/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Cafeteria": "Cafeteria",
    "Done": "Done",
    "Error while parsing informations": "Error while parsing informations",
    "FRIDAY": "FRIDAY",
    "Loading data ...": "Loading data ...",
    "MONDAY": "MONDAY",
    "Parsing data ...": "Parsing data ...",
    "Parsing menus ...": "Parsing menus ...",
    "Parsing week ...": "Parsing week ...",
    "Ready!": "\"Ready!\"",
    "Show price for": "Show price for",
    "source url has changed!": "source url has changed!",
    "THURSDAY": "THURSDAY",
    "title": "Cafeteria menu",
    "TUESDAY": "TUESDAY",
    "Update data manually": "Update data manually",
    "WEDNESDAY": "WEDNESDAY"
};



