/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Cafeteria": "Mensa",
    "Done": "Fertig",
    "Error while parsing informations": "Fehler beim Analysieren der Seite",
    "Friday": "Freitag",
    "Loading data ...": "Lade Daten ...",
    "Monday": "Montag",
    "Parsing data ...": "Analysiere Daten ...",
    "Parsing menus ...": "Analysiere Menüs ...",
    "Parsing week ...": "Analysiere Woche ...",
    "Ready!": "Fertig!",
    "Show Price For": "Mensa",
    "source url has changed!": "Adresse hat sich geändert!",
    "Thursday": "Donnerstag",
    "title": "Mensa Speiseplan",
    "Tuesday": "Dienstag",
    "Update data manually": "Daten manuell neu laden",
    "Wednesday": "Mittwoch"
};

